import React from "react";
import "../Footer/style.css";

function index() {
<<<<<<< HEAD
    return (
        <div className="main-footer">
            <div className="container">
                < div className ="row">
               
                
               
                <div className="col-sm-3">
                     
                <img src="/assets/slogo.png" className="foot-pic" alt="logopic" width="100" height="100"></img>
                </div>
                {/* Column 1  */}

                <div className="col-sm-3">
                     <a id="aboutLink" href="/about"><i className="link nav-link">About</i></a>
                      
                </div>
                     {/* Column 2  */}

                     <div className="col-sm-3">
                     <a id="blogLink" href="/blog" ><i className="link nav-link">Blog</i></a>
                      
                </div>

                     {/* Column 3  */}

                
                     <div className="col-sm-3">
                     <a id="contactLink" href="https://github.com/BrennanPredmore/jobless"><i className="fab fa-github">Connect</i></a>
                   
         


                </div>
         
                
              
                </div>
               
            </div>
            <div className="col-sm-12 copyright" >
                <p className="text-xs-center">© Copyright
             
             <a href="https://github.com/BrennanPredmore/jobless">Click here the Github Repo</a>
             (Generated by REACT.JS)  </p>
                </div>
        </div>
              
        

            

  
  
    )
=======
  return (
    <div className="main-footer">
      <div className="row">
        <div className="col-sm-1">
          <img
            src="/assets/slogo.png"
            className="foot-pic"
            alt="logopic"
            width="100%"
            height="100%"
          ></img>
        </div>

        <div className="col-sm-9 container text-center">
          <div className="row justify-content-center">
            <div className="col-sm-3">
              <a id="aboutLink" href="/about">
                <i className="link nav-link">About</i>
              </a>
            </div>

            <div className="col-sm-3">
              <a id="blogLink" href="/blog">
                <i className="link nav-link">Blog</i>
              </a>
            </div>

            <div className="col-sm-3">
              <a
                id="contactLink"
                href="https://github.com/BrennanPredmore/jobless"
              >
                <i className="fab fa-github">Connect</i>
              </a>
            </div>
          </div>
        </div>
      </div>

      <div div className="row">
        <div className="col-sm-12 copyright">
          <p className="text-xs-center">
            © Copyright
            <a href="https://github.com/BrennanPredmore/jobless">
              Click here the Github Repo
            </a>
            (Generated by REACT.JS){" "}
          </p>
        </div>
      </div>
    </div>
  );
>>>>>>> ee2e8dcd... footer is smaller,centered, logo is a normal size now
}

export default index;
